name: Cypress UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      CYPRESS_username: ${{ secrets.CYPRESS_USERNAME }}
      CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
      REACT_APP_API_URL: http://localhost:4000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Start backend server
        working-directory: backend
        run: npm start &
      
      - name: Start frontend server
        working-directory: frontend
        run: npm start &

      - name: Wait for servers to be ready
        run: |
          echo "Waiting for frontend and backend..."
          for i in {1..30}; do
            FRONTEND=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
            BACKEND=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:4000)
            if [ "$FRONTEND" == "200" ] && [ "$BACKEND" == "200" ]; then
              echo "✅ Frontend and backend are up!"
              break
            fi
            echo "⏳ Still waiting... ($i)"
            sleep 5
          done

      - name: Install Cypress
        working-directory: test/cypress
        run: npm install

      - name: Run Cypress tests
        working-directory: test/cypress
        run: npx cypress run
